config/routes.rb
Sample::Application.routes.draw do
	resources :users

	match '/signup', :to => 'users#new'
	match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
	root :to => 'pages#home' 
	 

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#


class User < ActiveRecord::Base
	attr_accessor :password 
 	attr_accessible :name, :email, :password, :password_confirmation

	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i	 
	
	validates :name,presence:true,length:{maximum:50}
	validates :email,presence:true,format:{ with:email_regex },uniqueness:{case_sensitive:false}
	validates :password, :presence  => true,:confirmation => true,:length => { :within => 6..40 }	
	
	before_save :encrypt_password
	
	def has_password? (submitted_password)
		encrypted_password == encrypt(submitted_password)
	end
	
	def self.authenticate(email, submitted_password)
    	user = find_by_email(email)
    	return nil  if user.nil?
    	return user if user.has_password?(submitted_password)
  	end	
	
	private
		def encrypt_password
			self.salt = make_salt if new_record?
			self.encrypted_password = encrypt(password)
		end
		def encrypt(string)
     		secure_hash("#{salt}--#{string}")
   		end

   		def make_salt
      		secure_hash("#{Time.now.utc}--#{password}")
    	end

    	def secure_hash(string)
      		Digest::SHA2.hexdigest(string)
    	end
    	
    	
end
	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end
class String
  def shuffle
    self.split('').shuffle.join
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end

  def about
    @title = "About"
  end

  def help
    @title = "Help"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def show
		@user = User.find(params[:id])
		@title = @user.name
	end
 
  def new
  	@title = "Sign up"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "ROR"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end

  end
  def logo
  	return image_tag("logo.png", :alt => "Sample App1", :class => "round")
  end
  
  def gravatar_for(user, options = {size:50})
  	return gravatar_image_tag(user.email.downcase, class:"gravatar",alt:user.name, gravatar:options)
  end
  
  
end

app/helpers/pages_helper.rb
module PagesHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %> 
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "Sign in", '#' %></li>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheet.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheet' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
  This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
  This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>
  <%= "Hello".shuffle %>
  <br>This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>

app/views/pages/home.html.erb
<h1>Home</h1>
<p>
  This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>
<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>